# Generated by Django 4.2.2 on 2023-07-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_account',
            field=models.BooleanField(default=False),
        ),
    ]
