# Generated by Django 4.2.2 on 2023-07-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
    ]
