# Generated by Django 4.2.2 on 2023-07-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_account_number',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
